import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/next"
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster
          theme="dark"
          className="toaster-purple"
          position="top-right"
          toastOptions={{
              style: {
                  background: "rgba(88, 28, 135, 0.15)",
                  backdropFilter: "blur(8px)",
                  border: "1px solid rgba(147, 51, 234, 0.3)",
                  color: "rgb(216, 180, 254)",
                  fontWeight: "500",
                  marginTop: "2.5rem",
              },
              actionButtonStyle: {
                  backgroundColor: "rgb(147, 51, 234)",
                  color: "white",
              },
          }}
      />
      <Navbar />
        {children}
      <Analytics />
      <Footer />
      </body>
    </html>
  );
}
