-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isBooked" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "link" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Queries" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isSolved" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "company" DROP NOT NULL;
